/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControlRolUsuario;
import controlador.ControlUsuario;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.RolUsuario;
import modelo.Usuario;
import utils.Util;

/**
 *
 * @author merarimaysosa
 */
public class Admin_Usuarios extends javax.swing.JFrame {

  private List<Usuario> usuarios;
  private JFrame anterior;

  /**
   * Creates new form Admin_Usuarios
   */
  public Admin_Usuarios(JFrame anterior) {
    initComponents();
    this.anterior = anterior;
    this.setResizable(false);
    this.setLocationRelativeTo(null);
    ControlUsuario usuario = new ControlUsuario();
    usuarios = usuario.listarTodos();
    this.tablaUsuario.setModel(usuario.getTableModel(usuarios));
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panel = new javax.swing.JPanel();
    botones = new javax.swing.JPanel();
    btnBusqueda = new javax.swing.JButton();
    actualizar = new javax.swing.JButton();
    agregar = new javax.swing.JButton();
    eliminar = new javax.swing.JButton();
    regresar = new javax.swing.JButton();
    busq = new javax.swing.JTextField();
    title = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    tablaUsuario = new javax.swing.JTable();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    panel.setBackground(new java.awt.Color(255, 255, 255));

    botones.setBackground(new java.awt.Color(204, 204, 255));
    botones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 3));

    btnBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
    btnBusqueda.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBusquedaActionPerformed(evt);
      }
    });

    actualizar.setText("Actualizar");
    actualizar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        actualizarActionPerformed(evt);
      }
    });

    agregar.setText("Agregar");
    agregar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        agregarActionPerformed(evt);
      }
    });

    eliminar.setText("Eliminar");
    eliminar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        eliminarActionPerformed(evt);
      }
    });

    regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/return.png"))); // NOI18N
    regresar.setBorder(null);
    regresar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        regresarActionPerformed(evt);
      }
    });

    busq.setText("Buscar");
    busq.setToolTipText("");

    title.setFont(new java.awt.Font("Cute Cartoon", 1, 48)); // NOI18N
    title.setText("Administración de Usuarios");

    javax.swing.GroupLayout botonesLayout = new javax.swing.GroupLayout(botones);
    botones.setLayout(botonesLayout);
    botonesLayout.setHorizontalGroup(
      botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(botonesLayout.createSequentialGroup()
        .addContainerGap(32, Short.MAX_VALUE)
        .addGroup(botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonesLayout.createSequentialGroup()
            .addComponent(title)
            .addGap(46, 46, 46)
            .addComponent(regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(40, 40, 40))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonesLayout.createSequentialGroup()
            .addComponent(busq, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(27, 27, 27)
            .addComponent(actualizar)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(agregar)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(eliminar)
            .addGap(32, 32, 32))))
    );

    botonesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {actualizar, agregar, eliminar});

    botonesLayout.setVerticalGroup(
      botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonesLayout.createSequentialGroup()
        .addContainerGap(8, Short.MAX_VALUE)
        .addGroup(botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(regresar)
          .addComponent(title))
        .addGap(10, 10, 10)
        .addGroup(botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btnBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(actualizar)
            .addComponent(agregar)
            .addComponent(eliminar)
            .addComponent(busq, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(15, 15, 15))
    );

    busq.getAccessibleContext().setAccessibleDescription("Buscar");

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));

    tablaUsuario.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null},
        {null, null, null},
        {null, null, null},
        {null, null, null},
        {null, null, null},
        {null, null, null},
        {null, null, null},
        {null, null, null},
        {null, null, null},
        {null, null, null}
      },
      new String [] {
        "Usuario", "Rol", "Contraseña"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.String.class, java.lang.String.class
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }
    });
    jScrollPane1.setViewportView(tablaUsuario);
    if (tablaUsuario.getColumnModel().getColumnCount() > 0) {
      tablaUsuario.getColumnModel().getColumn(0).setResizable(false);
      tablaUsuario.getColumnModel().getColumn(1).setResizable(false);
      tablaUsuario.getColumnModel().getColumn(2).setResizable(false);
    }

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(23, 23, 23)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(23, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(18, 18, 18)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(21, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
    panel.setLayout(panelLayout);
    panelLayout.setHorizontalGroup(
      panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(botones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    panelLayout.setVerticalGroup(
      panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelLayout.createSequentialGroup()
        .addComponent(botones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void btnBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaActionPerformed
      // TODO add your handling code here:
      String match = this.busq.getText().trim();
      List<Usuario> busqueda = new LinkedList<>(this.usuarios.stream()
              .filter(usu -> usu.getNombre().contains(match))
              .toList());
      ControlUsuario usuario = new ControlUsuario();
      Util.renderizarTabla(tablaUsuario, this, busq, usuarios, busqueda, match, usuario);
    }//GEN-LAST:event_btnBusquedaActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
      // TODO add your handling code here:
        this.setVisible(false);
        anterior.setVisible(true);
    }//GEN-LAST:event_regresarActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
      // TODO add your handling code here:
      Usuarios_Agregar ventana = new Usuarios_Agregar(this);
      this.setVisible(false);
      ventana.setVisible(true);
    }//GEN-LAST:event_agregarActionPerformed

  private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
    // TODO add your handling code here:
    int filaSeleccionada = this.tablaUsuario.getSelectedRow();
    if (filaSeleccionada == -1) {
      JOptionPane.showMessageDialog(this, "Seleccione una fila para realizar esta operación",
              "Upsi!", JOptionPane.WARNING_MESSAGE);
    } else {
      String folioUsu = this.tablaUsuario.getValueAt(filaSeleccionada, 0).toString();
      String nombreUsu = this.tablaUsuario.getValueAt(filaSeleccionada, 1).toString();
      String rolUsu = this.tablaUsuario.getValueAt(filaSeleccionada, 2).toString();
      String pwdUsu = this.tablaUsuario.getValueAt(filaSeleccionada, 3).toString();

      Usuario usu = new Usuario(folioUsu, nombreUsu, pwdUsu, new RolUsuario(rolUsu));
      ControlUsuario usuario = new ControlUsuario();
      if (usuario.actualizar(usu)) {
        JOptionPane.showMessageDialog(this, "Categoria actualizada con éxito",
                "Eureka!", JOptionPane.INFORMATION_MESSAGE);
      } else {
        JOptionPane.showMessageDialog(this, "Algo salió mal, intente más tarde",
                "Oh no!", JOptionPane.ERROR_MESSAGE);
      }
    }
  }//GEN-LAST:event_actualizarActionPerformed

  private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
    // TODO add your handling code here:
    Util.eliminarRegistro(this.tablaUsuario, new ControlUsuario(), this);
  }//GEN-LAST:event_eliminarActionPerformed

  /**
   * @param args the command line arguments
   */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Admin_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Admin_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Admin_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Admin_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Admin_Usuarios().setVisible(true);
//            }
//        });
//    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton actualizar;
  private javax.swing.JButton agregar;
  private javax.swing.JPanel botones;
  private javax.swing.JButton btnBusqueda;
  private javax.swing.JTextField busq;
  private javax.swing.JButton eliminar;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JPanel panel;
  private javax.swing.JButton regresar;
  private javax.swing.JTable tablaUsuario;
  private javax.swing.JLabel title;
  // End of variables declaration//GEN-END:variables
}
