/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControlProveedor;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Proveedor;

/**
 *
 * @author merarimaysosa
 */
public class Inventario_Agregar_Proveedor extends javax.swing.JFrame {
    private JFrame anterior;
    /**
     * Creates new form Usuarios_Agregar
     */
    public Inventario_Agregar_Proveedor(JFrame anterior) {
        initComponents();
        this.anterior = anterior;
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panel = new javax.swing.JPanel();
    divs = new javax.swing.JPanel();
    imgs = new javax.swing.JPanel();
    img_logo = new javax.swing.JPanel();
    txt = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    boton_dentro = new javax.swing.JPanel();
    agregar = new javax.swing.JButton();
    regresa = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    data = new javax.swing.JPanel();
    jLabel5 = new javax.swing.JLabel();
    campoDescripCont = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    campoNombre = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    campoRFC = new javax.swing.JTextField();
    campoNombreCont = new javax.swing.JTextField();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    campoSitioWeb = new javax.swing.JTextField();
    jLabel15 = new javax.swing.JLabel();
    campoCalle = new javax.swing.JTextField();
    jLabel17 = new javax.swing.JLabel();
    campoCorreo = new javax.swing.JTextField();
    jPanel1 = new javax.swing.JPanel();
    jLabel10 = new javax.swing.JLabel();
    campoNumExt = new javax.swing.JTextField();
    jLabel11 = new javax.swing.JLabel();
    campoNumInt = new javax.swing.JTextField();
    jLabel12 = new javax.swing.JLabel();
    campoEstado = new javax.swing.JTextField();
    campoCiudad = new javax.swing.JTextField();
    jLabel13 = new javax.swing.JLabel();
    jLabel14 = new javax.swing.JLabel();
    campoCP = new javax.swing.JTextField();
    jLabel16 = new javax.swing.JLabel();
    campoTelefono = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    divs.setLayout(new java.awt.GridLayout(1, 2));

    img_logo.setBackground(new java.awt.Color(255, 255, 255));
    img_logo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 3));

    txt.setFont(new java.awt.Font("Cute Cartoon", 1, 36)); // NOI18N
    txt.setText("Agregar proveedor");

    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categorias.png"))); // NOI18N

    boton_dentro.setBackground(new java.awt.Color(204, 204, 255));
    boton_dentro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    agregar.setText("Agregar");
    agregar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        agregarActionPerformed(evt);
      }
    });

    regresa.setText("Regresar");
    regresa.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        regresaActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout boton_dentroLayout = new javax.swing.GroupLayout(boton_dentro);
    boton_dentro.setLayout(boton_dentroLayout);
    boton_dentroLayout.setHorizontalGroup(
      boton_dentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(boton_dentroLayout.createSequentialGroup()
        .addGap(32, 32, 32)
        .addGroup(boton_dentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(agregar)
          .addComponent(regresa))
        .addContainerGap(32, Short.MAX_VALUE))
    );

    boton_dentroLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {agregar, regresa});

    boton_dentroLayout.setVerticalGroup(
      boton_dentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boton_dentroLayout.createSequentialGroup()
        .addContainerGap(25, Short.MAX_VALUE)
        .addComponent(agregar)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(regresa)
        .addGap(25, 25, 25))
    );

    boton_dentroLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {agregar, regresa});

    jLabel2.setFont(new java.awt.Font("Baskerville", 1, 24)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(153, 153, 255));
    jLabel2.setText(" INVENTARIOS");

    javax.swing.GroupLayout img_logoLayout = new javax.swing.GroupLayout(img_logo);
    img_logo.setLayout(img_logoLayout);
    img_logoLayout.setHorizontalGroup(
      img_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(img_logoLayout.createSequentialGroup()
        .addGroup(img_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(img_logoLayout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addGroup(img_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(txt)))
          .addGroup(img_logoLayout.createSequentialGroup()
            .addGap(78, 78, 78)
            .addComponent(jLabel1))
          .addGroup(img_logoLayout.createSequentialGroup()
            .addGap(33, 33, 33)
            .addComponent(boton_dentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(11, Short.MAX_VALUE))
    );
    img_logoLayout.setVerticalGroup(
      img_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(img_logoLayout.createSequentialGroup()
        .addGap(57, 57, 57)
        .addComponent(jLabel2)
        .addGap(18, 18, 18)
        .addComponent(txt)
        .addGap(37, 37, 37)
        .addComponent(jLabel1)
        .addGap(53, 53, 53)
        .addComponent(boton_dentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(89, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout imgsLayout = new javax.swing.GroupLayout(imgs);
    imgs.setLayout(imgsLayout);
    imgsLayout.setHorizontalGroup(
      imgsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(img_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    imgsLayout.setVerticalGroup(
      imgsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(img_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    divs.add(imgs);

    data.setBackground(new java.awt.Color(204, 204, 255));
    data.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 3));

    jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    jLabel5.setText("RFC:");

    jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    jLabel6.setText("Nombre:");

    jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    jLabel7.setText("Nombre de contacto:");

    jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    jLabel8.setText("Calle:");

    jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    jLabel9.setText("Descripción de contacto:");

    jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    jLabel15.setText("Correo:");

    jLabel17.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    jLabel17.setText("Sitio Web:");

    javax.swing.GroupLayout dataLayout = new javax.swing.GroupLayout(data);
    data.setLayout(dataLayout);
    dataLayout.setHorizontalGroup(
      dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(dataLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(dataLayout.createSequentialGroup()
            .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel9)
              .addComponent(jLabel8)
              .addComponent(jLabel15)
              .addComponent(jLabel17))
            .addGap(0, 0, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataLayout.createSequentialGroup()
            .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(campoSitioWeb, javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(campoCorreo, javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(campoRFC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
              .addComponent(campoNombre, javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(campoNombreCont, javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dataLayout.createSequentialGroup()
                .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel5)
                  .addComponent(jLabel7)
                  .addComponent(jLabel6))
                .addGap(0, 0, Short.MAX_VALUE))
              .addComponent(campoDescripCont, javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(campoCalle))
            .addContainerGap())))
    );
    dataLayout.setVerticalGroup(
      dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(dataLayout.createSequentialGroup()
        .addGap(17, 17, 17)
        .addComponent(jLabel5)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(campoRFC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel6)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel7)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(campoNombreCont, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel9)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(campoDescripCont, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel8)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(campoCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel15)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(campoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel17)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(campoSitioWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(21, Short.MAX_VALUE))
    );

    dataLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {campoDescripCont, campoNombre});

    divs.add(data);

    jPanel1.setBackground(new java.awt.Color(204, 204, 255));
    jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 3));

    jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    jLabel10.setText("Número interior:");

    jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    jLabel11.setText("Número exterior:");

    jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    jLabel12.setText("Estado:");

    jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    jLabel13.setText("Ciudad:");

    jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    jLabel14.setText("Código Postal:");

    jLabel16.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    jLabel16.setText("Teléfono:");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel11)
              .addComponent(jLabel10)
              .addComponent(jLabel12)
              .addComponent(jLabel13)
              .addComponent(jLabel14)
              .addComponent(jLabel16))
            .addGap(0, 0, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(campoTelefono, javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(campoEstado, javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(campoNumInt, javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(campoNumExt, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
              .addComponent(campoCiudad)
              .addComponent(campoCP))
            .addContainerGap())))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(15, 15, 15)
        .addComponent(jLabel11)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(campoNumExt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel10)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(campoNumInt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel12)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(campoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(5, 5, 5)
        .addComponent(jLabel13)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(campoCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel14)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(campoCP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabel16)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(82, Short.MAX_VALUE))
    );

    divs.add(jPanel1);

    javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
    panel.setLayout(panelLayout);
    panelLayout.setHorizontalGroup(
      panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelLayout.createSequentialGroup()
        .addComponent(divs, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );
    panelLayout.setVerticalGroup(
      panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(divs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void regresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        anterior.setVisible(true);
    }//GEN-LAST:event_regresaActionPerformed

  private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
    // TODO add your handling code here:
    String rfc = this.campoRFC.getText();
    String nombre = this.campoNombre.getText();
    String contNombre = this.campoNombreCont.getText();
    String contDescrip = this.campoDescripCont.getText();
    String calle = this.campoCalle.getText();
    String numExt = this.campoNumExt.getText();
    String numInt = this.campoNumInt.getText();
    String estado = this.campoEstado.getText();
    String ciudad = this.campoCiudad.getText();
    String cp = this.campoCP.getText();
    String correo = this.campoCorreo.getText();
    String telefono = this.campoTelefono.getText();
    String sitioW = this.campoSitioWeb.getText();

    ControlProveedor proveedor = new ControlProveedor();
    Proveedor prov = new Proveedor(rfc, nombre, contNombre,
      contDescrip, calle, numExt, numInt, estado, ciudad,
      cp, correo, telefono, sitioW);

    if (proveedor.insertar(prov)) {
      JOptionPane.showMessageDialog(this, "Proveedor agragado con éxito",
        "Eureka!", JOptionPane.INFORMATION_MESSAGE);
      this.campoCP.setText("");
      this.campoCalle.setText("");
      this.campoCiudad.setText("");
      this.campoCorreo.setText("");
      this.campoDescripCont.setText("");
      this.campoEstado.setText("");
      this.campoNombre.setText("");
      this.campoNombreCont.setText("");
      this.campoNumInt.setText("");
      this.campoNumExt.setText("");
      this.campoRFC.setText("");
      this.campoSitioWeb.setText("");
      this.campoTelefono.setText("");
    } else {
      JOptionPane.showMessageDialog(this, "Algo salió mal, intente más tarde",
        "Oh no!", JOptionPane.ERROR_MESSAGE);
    }
  }//GEN-LAST:event_agregarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Inventario_Agregar_Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Inventario_Agregar_Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Inventario_Agregar_Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Inventario_Agregar_Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Inventario_Agregar_Proveedor().setVisible(true);
//            }
//        });
//    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton agregar;
  private javax.swing.JPanel boton_dentro;
  private javax.swing.JTextField campoCP;
  private javax.swing.JTextField campoCalle;
  private javax.swing.JTextField campoCiudad;
  private javax.swing.JTextField campoCorreo;
  private javax.swing.JTextField campoDescripCont;
  private javax.swing.JTextField campoEstado;
  private javax.swing.JTextField campoNombre;
  private javax.swing.JTextField campoNombreCont;
  private javax.swing.JTextField campoNumExt;
  private javax.swing.JTextField campoNumInt;
  private javax.swing.JTextField campoRFC;
  private javax.swing.JTextField campoSitioWeb;
  private javax.swing.JTextField campoTelefono;
  private javax.swing.JPanel data;
  private javax.swing.JPanel divs;
  private javax.swing.JPanel img_logo;
  private javax.swing.JPanel imgs;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel14;
  private javax.swing.JLabel jLabel15;
  private javax.swing.JLabel jLabel16;
  private javax.swing.JLabel jLabel17;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel panel;
  private javax.swing.JButton regresa;
  private javax.swing.JLabel txt;
  // End of variables declaration//GEN-END:variables
}
