/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControlCategoria;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Categoria;
import utils.Util;

/**
 *
 * @author merarimaysosa
 */
public class Inventario_Agregar_Categoria extends javax.swing.JFrame {
  
  private JFrame anterior;

    /**
     * Creates new form Usuarios_Agregar
   * @param anterior
     */
    public Inventario_Agregar_Categoria(JFrame anterior) {
        initComponents();
        this.anterior = anterior;
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panel = new javax.swing.JPanel();
    divs = new javax.swing.JPanel();
    imgs = new javax.swing.JPanel();
    img_logo = new javax.swing.JPanel();
    txt = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    boton_dentro = new javax.swing.JPanel();
    agregar = new javax.swing.JButton();
    regresa = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    data = new javax.swing.JPanel();
    jLabel6 = new javax.swing.JLabel();
    jTextField2 = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    divs.setLayout(new java.awt.GridLayout(1, 2));

    img_logo.setBackground(new java.awt.Color(255, 255, 255));
    img_logo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 3));

    txt.setFont(new java.awt.Font("Cute Cartoon", 1, 36)); // NOI18N
    txt.setText("Agregar categoría");

    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categorias.png"))); // NOI18N

    boton_dentro.setBackground(new java.awt.Color(204, 204, 255));
    boton_dentro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    agregar.setText("Agregar");
    agregar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        agregarActionPerformed(evt);
      }
    });

    regresa.setText("Regresar");
    regresa.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        regresaActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout boton_dentroLayout = new javax.swing.GroupLayout(boton_dentro);
    boton_dentro.setLayout(boton_dentroLayout);
    boton_dentroLayout.setHorizontalGroup(
      boton_dentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(boton_dentroLayout.createSequentialGroup()
        .addGap(32, 32, 32)
        .addGroup(boton_dentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(agregar)
          .addComponent(regresa))
        .addContainerGap(32, Short.MAX_VALUE))
    );

    boton_dentroLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {agregar, regresa});

    boton_dentroLayout.setVerticalGroup(
      boton_dentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boton_dentroLayout.createSequentialGroup()
        .addContainerGap(25, Short.MAX_VALUE)
        .addComponent(agregar)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(regresa)
        .addGap(25, 25, 25))
    );

    boton_dentroLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {agregar, regresa});

    jLabel2.setFont(new java.awt.Font("Baskerville", 1, 24)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(153, 153, 255));
    jLabel2.setText(" INVENTARIOS");

    javax.swing.GroupLayout img_logoLayout = new javax.swing.GroupLayout(img_logo);
    img_logo.setLayout(img_logoLayout);
    img_logoLayout.setHorizontalGroup(
      img_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, img_logoLayout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(boton_dentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(30, 30, 30))
      .addGroup(img_logoLayout.createSequentialGroup()
        .addGroup(img_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(img_logoLayout.createSequentialGroup()
            .addGap(90, 90, 90)
            .addComponent(jLabel1))
          .addGroup(img_logoLayout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addGroup(img_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    img_logoLayout.setVerticalGroup(
      img_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(img_logoLayout.createSequentialGroup()
        .addContainerGap(25, Short.MAX_VALUE)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(txt)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabel1)
        .addGap(18, 18, 18)
        .addComponent(boton_dentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(30, 30, 30))
    );

    javax.swing.GroupLayout imgsLayout = new javax.swing.GroupLayout(imgs);
    imgs.setLayout(imgsLayout);
    imgsLayout.setHorizontalGroup(
      imgsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(img_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    imgsLayout.setVerticalGroup(
      imgsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(img_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    divs.add(imgs);

    data.setBackground(new java.awt.Color(204, 204, 255));
    data.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 3));

    jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
    jLabel6.setText("Nombre:");

    jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
    jLabel7.setText("Descripción:");

    jTextArea1.setColumns(20);
    jTextArea1.setRows(5);
    jScrollPane1.setViewportView(jTextArea1);

    javax.swing.GroupLayout dataLayout = new javax.swing.GroupLayout(data);
    data.setLayout(dataLayout);
    dataLayout.setHorizontalGroup(
      dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(dataLayout.createSequentialGroup()
        .addGap(33, 33, 33)
        .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
          .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
        .addGap(31, 31, 31))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataLayout.createSequentialGroup()
            .addComponent(jLabel6)
            .addGap(80, 80, 80))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataLayout.createSequentialGroup()
            .addComponent(jLabel7)
            .addGap(63, 63, 63))))
    );
    dataLayout.setVerticalGroup(
      dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(dataLayout.createSequentialGroup()
        .addGap(76, 76, 76)
        .addComponent(jLabel6)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(30, 30, 30)
        .addComponent(jLabel7)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(62, Short.MAX_VALUE))
    );

    divs.add(data);

    javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
    panel.setLayout(panelLayout);
    panelLayout.setHorizontalGroup(
      panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(divs, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    panelLayout.setVerticalGroup(
      panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(divs, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void regresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        anterior.setVisible(true);
    }//GEN-LAST:event_regresaActionPerformed

  private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
    // TODO add your handling code here:
    String nombre = this.jTextField2.getText();
    String descripcion = this.jTextArea1.getText();
    
    ControlCategoria categoria = new ControlCategoria();
    List<Categoria> lista = categoria.listarTodos();
    int cantidadCategorias = lista.size();
    int siguiente = cantidadCategorias + 1;
    
    String folioCat = Util.generarFolio("CAT", String.valueOf(siguiente));
    Categoria cat = new Categoria(folioCat, nombre, descripcion);
    
    if (categoria.insertar(cat)) {
      JOptionPane.showMessageDialog(this, "Categoria agregado con éxito",
        "Eureka!", JOptionPane.INFORMATION_MESSAGE);
      this.jTextField2.setText("");
      this.jTextArea1.setText("");
    } else {
      JOptionPane.showMessageDialog(this, "Algo salió mal, intente más tarde",
        "Oh no!", JOptionPane.ERROR_MESSAGE);
    }
  }//GEN-LAST:event_agregarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Inventario_Agregar_Categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Inventario_Agregar_Categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Inventario_Agregar_Categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Inventario_Agregar_Categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Inventario_Agregar_Categoria().setVisible(true);
//            }
//        });
//    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton agregar;
  private javax.swing.JPanel boton_dentro;
  private javax.swing.JPanel data;
  private javax.swing.JPanel divs;
  private javax.swing.JPanel img_logo;
  private javax.swing.JPanel imgs;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea jTextArea1;
  private javax.swing.JTextField jTextField2;
  private javax.swing.JPanel panel;
  private javax.swing.JButton regresa;
  private javax.swing.JLabel txt;
  // End of variables declaration//GEN-END:variables
}
