/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControlCategoria;
import controlador.ControlProducto;
import controlador.ControlProveedor;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Categoria;
import modelo.Producto;
import modelo.Proveedor;
import utils.Util;

/**
 *
 * @author merarimaysosa
 */
public class Inventario_Agregar_Producto extends javax.swing.JFrame {
  private JFrame anterior;
  /**
   * Creates new form Usuarios_Agregar
   * @param anterior
   */
  public Inventario_Agregar_Producto(JFrame anterior) {
    initComponents();
    this.anterior = anterior;
    this.setLocationRelativeTo(null);
    this.setResizable(false);

    ControlProveedor proveedor = new ControlProveedor();
    List<Proveedor> list = proveedor.listarTodos();
    ArrayList<String> arrlist = new ArrayList();
    for (Proveedor prov : list) {
      arrlist.add(prov.getRfc());
    }
    this.comboProveedor.setModel(new DefaultComboBoxModel(arrlist.toArray(String[]::new)));

    ControlCategoria categoria = new ControlCategoria();
    List<Categoria> list2 = categoria.listarTodos();
    ArrayList<String> arrlist2 = new ArrayList();
    for (Categoria cat : list2) {
      arrlist2.add(cat.getNombre());
    }
    this.comboCategoria.setModel(new DefaultComboBoxModel(arrlist2.toArray(String[]::new)));
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panel = new javax.swing.JPanel();
    divs = new javax.swing.JPanel();
    imgs = new javax.swing.JPanel();
    img_logo = new javax.swing.JPanel();
    txt = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    boton_dentro = new javax.swing.JPanel();
    agregar = new javax.swing.JButton();
    regresa = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    data = new javax.swing.JPanel();
    campoPrecio = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    campoNombre = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    campoMedidaDesc = new javax.swing.JTextField();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    campoCantidad = new javax.swing.JTextField();
    jPanel1 = new javax.swing.JPanel();
    jLabel10 = new javax.swing.JLabel();
    campoLimiteStock = new javax.swing.JTextField();
    jLabel11 = new javax.swing.JLabel();
    campoDescont = new javax.swing.JTextField();
    jLabel12 = new javax.swing.JLabel();
    jLabel13 = new javax.swing.JLabel();
    comboProveedor = new javax.swing.JComboBox<>();
    comboCategoria = new javax.swing.JComboBox<>();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    divs.setLayout(new java.awt.GridLayout(1, 2));

    img_logo.setBackground(new java.awt.Color(255, 255, 255));
    img_logo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 3));

    txt.setFont(new java.awt.Font("Cute Cartoon", 1, 36)); // NOI18N
    txt.setText("Agregar productos");

    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categorias.png"))); // NOI18N

    boton_dentro.setBackground(new java.awt.Color(204, 204, 255));
    boton_dentro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    agregar.setText("Agregar");
    agregar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        agregarActionPerformed(evt);
      }
    });

    regresa.setText("Regresar");
    regresa.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        regresaActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout boton_dentroLayout = new javax.swing.GroupLayout(boton_dentro);
    boton_dentro.setLayout(boton_dentroLayout);
    boton_dentroLayout.setHorizontalGroup(
      boton_dentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(boton_dentroLayout.createSequentialGroup()
        .addGap(32, 32, 32)
        .addGroup(boton_dentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(agregar)
          .addComponent(regresa))
        .addContainerGap(32, Short.MAX_VALUE))
    );

    boton_dentroLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {agregar, regresa});

    boton_dentroLayout.setVerticalGroup(
      boton_dentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boton_dentroLayout.createSequentialGroup()
        .addContainerGap(25, Short.MAX_VALUE)
        .addComponent(agregar)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(regresa)
        .addGap(25, 25, 25))
    );

    boton_dentroLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {agregar, regresa});

    jLabel2.setFont(new java.awt.Font("Baskerville", 1, 24)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(153, 153, 255));
    jLabel2.setText(" INVENTARIOS");

    javax.swing.GroupLayout img_logoLayout = new javax.swing.GroupLayout(img_logo);
    img_logo.setLayout(img_logoLayout);
    img_logoLayout.setHorizontalGroup(
      img_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(img_logoLayout.createSequentialGroup()
        .addGroup(img_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(img_logoLayout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addGroup(img_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(txt)))
          .addGroup(img_logoLayout.createSequentialGroup()
            .addGap(78, 78, 78)
            .addComponent(jLabel1))
          .addGroup(img_logoLayout.createSequentialGroup()
            .addGap(37, 37, 37)
            .addComponent(boton_dentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(12, Short.MAX_VALUE))
    );
    img_logoLayout.setVerticalGroup(
      img_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(img_logoLayout.createSequentialGroup()
        .addGap(21, 21, 21)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(txt)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(boton_dentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(47, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout imgsLayout = new javax.swing.GroupLayout(imgs);
    imgs.setLayout(imgsLayout);
    imgsLayout.setHorizontalGroup(
      imgsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(img_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    imgsLayout.setVerticalGroup(
      imgsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(img_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    divs.add(imgs);

    data.setBackground(new java.awt.Color(204, 204, 255));
    data.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 3));

    jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    jLabel6.setText("Nombre:");

    jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    jLabel7.setText("Medida de descripción:");

    jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    jLabel8.setText("Cantidad:");

    jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    jLabel9.setText("Precio:");

    javax.swing.GroupLayout dataLayout = new javax.swing.GroupLayout(data);
    data.setLayout(dataLayout);
    dataLayout.setHorizontalGroup(
      dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(dataLayout.createSequentialGroup()
            .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel9)
              .addComponent(jLabel8))
            .addGap(164, 164, 164))
          .addComponent(campoNombre)
          .addComponent(campoMedidaDesc)
          .addGroup(dataLayout.createSequentialGroup()
            .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel7)
              .addComponent(jLabel6))
            .addGap(0, 0, Short.MAX_VALUE))
          .addComponent(campoPrecio)
          .addComponent(campoCantidad, javax.swing.GroupLayout.Alignment.TRAILING))
        .addContainerGap())
    );
    dataLayout.setVerticalGroup(
      dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(dataLayout.createSequentialGroup()
        .addGap(40, 40, 40)
        .addComponent(jLabel6)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel7)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(campoMedidaDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel9)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(campoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel8)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(campoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(46, Short.MAX_VALUE))
    );

    dataLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {campoNombre, campoPrecio});

    divs.add(data);

    jPanel1.setBackground(new java.awt.Color(204, 204, 255));
    jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 3));

    jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    jLabel10.setText("Descontinuado?");

    jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    jLabel11.setText("Límite en stock:");

    jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    jLabel12.setText("Proveedor:");

    jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    jLabel13.setText("Categoría:");

    comboProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    comboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(campoLimiteStock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(comboCategoria, 0, 225, Short.MAX_VALUE)
              .addComponent(jLabel11)
              .addComponent(jLabel10)
              .addComponent(jLabel12)
              .addComponent(jLabel13)
              .addComponent(comboProveedor, 0, 225, Short.MAX_VALUE)
              .addComponent(campoDescont))
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );

    jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {campoLimiteStock, comboCategoria, comboProveedor});

    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(37, 37, 37)
        .addComponent(jLabel11)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(campoLimiteStock, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel10)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(campoDescont, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(3, 3, 3)
        .addComponent(jLabel12)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(comboProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel13)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(52, Short.MAX_VALUE))
    );

    jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {campoDescont, campoLimiteStock, comboCategoria, comboProveedor});

    divs.add(jPanel1);

    javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
    panel.setLayout(panelLayout);
    panelLayout.setHorizontalGroup(
      panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelLayout.createSequentialGroup()
        .addComponent(divs, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );
    panelLayout.setVerticalGroup(
      panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(divs, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void regresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresaActionPerformed
      // TODO add your handling code here:
       this.setVisible(false);
       anterior.setVisible(true);
    }//GEN-LAST:event_regresaActionPerformed

  private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
    // TODO add your handling code here:
    String nombre = this.campoNombre.getText();
    String medidaDes = this.campoMedidaDesc.getText();
    String precio = this.campoPrecio.getText();
    String cantidad = this.campoCantidad.getText();
    String limiteStock = this.campoLimiteStock.getText();
    String desc = this.campoDescont.getText();
    String rfc = this.comboProveedor.getSelectedItem().toString();
    int cat = this.comboCategoria.getSelectedIndex() + 1;

    String folioCat = Util.generarFolio("CAT", String.valueOf(cat));

    ControlProducto producto = new ControlProducto();
    List<Producto> lista = producto.listarTodos();
    int cantidadProductos = lista.size();
    int siguiente = cantidadProductos + 1;
    String clave = Util.generarFolio("PRD", String.valueOf(siguiente));
    Producto prd = new Producto(clave,
      nombre, medidaDes, Double.parseDouble(precio),
      Integer.parseInt(cantidad),
      Integer.parseInt(limiteStock),
      Short.parseShort(desc),
      new Proveedor(rfc),
      new Categoria(folioCat)
    );

    if (producto.insertar(prd)) {
      JOptionPane.showMessageDialog(this, "Producto agregado con éxito",
        "Eureka!", JOptionPane.INFORMATION_MESSAGE);
      this.campoCantidad.setText("");
      this.campoLimiteStock.setText("");
      this.campoDescont.setText("");
      this.campoMedidaDesc.setText("");
      this.campoNombre.setText("");
      this.campoPrecio.setText("");
    } else {
      JOptionPane.showMessageDialog(this, "Algo salió mal, intente más tarde",
        "Oh no!", JOptionPane.ERROR_MESSAGE);
    }
  }//GEN-LAST:event_agregarActionPerformed

  /**
   * @param args the command line arguments
   */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Inventario_Agregar_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Inventario_Agregar_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Inventario_Agregar_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Inventario_Agregar_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Inventario_Agregar_Producto().setVisible(true);
//            }
//        });
//    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton agregar;
  private javax.swing.JPanel boton_dentro;
  private javax.swing.JTextField campoCantidad;
  private javax.swing.JTextField campoDescont;
  private javax.swing.JTextField campoLimiteStock;
  private javax.swing.JTextField campoMedidaDesc;
  private javax.swing.JTextField campoNombre;
  private javax.swing.JTextField campoPrecio;
  private javax.swing.JComboBox<String> comboCategoria;
  private javax.swing.JComboBox<String> comboProveedor;
  private javax.swing.JPanel data;
  private javax.swing.JPanel divs;
  private javax.swing.JPanel img_logo;
  private javax.swing.JPanel imgs;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel panel;
  private javax.swing.JButton regresa;
  private javax.swing.JLabel txt;
  // End of variables declaration//GEN-END:variables
}
