/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author merarimaysosa
 */
public class Login_Vendedor extends javax.swing.JFrame {

    /**
     * Creates new form login_admin
     */
    public Login_Vendedor() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        usuario_vista = new javax.swing.JPanel();
        icono_user = new javax.swing.JLabel();
        user_nombre = new javax.swing.JLabel();
        cambia_user = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        usuarios = new javax.swing.JPanel();
        ver_usu = new javax.swing.JButton();
        logo_usu = new javax.swing.JLabel();
        ajustes = new javax.swing.JPanel();
        setting = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuario_vista.setBackground(new java.awt.Color(204, 204, 255));

        icono_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vendedora.png"))); // NOI18N

        user_nombre.setText("Hola, [usuario]");

        cambia_user.setText("Cerrar sesión");
        cambia_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambia_userActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout usuario_vistaLayout = new javax.swing.GroupLayout(usuario_vista);
        usuario_vista.setLayout(usuario_vistaLayout);
        usuario_vistaLayout.setHorizontalGroup(
            usuario_vistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuario_vistaLayout.createSequentialGroup()
                .addGroup(usuario_vistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cambia_user)
                    .addGroup(usuario_vistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(usuario_vistaLayout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addComponent(icono_user))
                        .addGroup(usuario_vistaLayout.createSequentialGroup()
                            .addGap(55, 55, 55)
                            .addComponent(user_nombre))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        usuario_vistaLayout.setVerticalGroup(
            usuario_vistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuario_vistaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(icono_user, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(user_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cambia_user)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        panel.add(usuario_vista, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 370));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        usuarios.setBackground(new java.awt.Color(255, 255, 255));
        usuarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        ver_usu.setText("Venta");
        ver_usu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_usuActionPerformed(evt);
            }
        });

        logo_usu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/compras.png"))); // NOI18N

        javax.swing.GroupLayout usuariosLayout = new javax.swing.GroupLayout(usuarios);
        usuarios.setLayout(usuariosLayout);
        usuariosLayout.setHorizontalGroup(
            usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuariosLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(ver_usu)
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usuariosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logo_usu, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        usuariosLayout.setVerticalGroup(
            usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usuariosLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(logo_usu, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ver_usu)
                .addGap(17, 17, 17))
        );

        jPanel1.add(usuarios);

        ajustes.setBackground(new java.awt.Color(255, 255, 255));
        ajustes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        setting.setText("Ayuda");
        setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/preparar.png"))); // NOI18N

        javax.swing.GroupLayout ajustesLayout = new javax.swing.GroupLayout(ajustes);
        ajustes.setLayout(ajustesLayout);
        ajustesLayout.setHorizontalGroup(
            ajustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ajustesLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(ajustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(setting)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
        ajustesLayout.setVerticalGroup(
            ajustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ajustesLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(setting)
                .addGap(16, 16, 16))
        );

        jPanel1.add(ajustes);

        panel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 180, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cambia_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambia_userActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_cambia_userActionPerformed

    private void settingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_settingActionPerformed

    private void ver_usuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_usuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Admin_Clientes().setVisible(true);
    }//GEN-LAST:event_ver_usuActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Login_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Login_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Login_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Login_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Login_Vendedor().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ajustes;
    private javax.swing.JButton cambia_user;
    private javax.swing.JLabel icono_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo_usu;
    private javax.swing.JPanel panel;
    private javax.swing.JButton setting;
    private javax.swing.JLabel user_nombre;
    private javax.swing.JPanel usuario_vista;
    private javax.swing.JPanel usuarios;
    private javax.swing.JButton ver_usu;
    // End of variables declaration//GEN-END:variables
}
