/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import modelo.Usuario;

/**
 *
 * @author merarimaysosa
 */
public class Login_Admin extends javax.swing.JFrame {
    
    private final Usuario usuario;

    /**
     * Creates new form login_admin
   * @param usuario
     */
    public Login_Admin(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.user_nombre.setText("Hola, "+this.usuario.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        usuario_vista = new javax.swing.JPanel();
        icono_user = new javax.swing.JLabel();
        user_nombre = new javax.swing.JLabel();
        cambia_user = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        usuarios = new javax.swing.JPanel();
        ver_usu = new javax.swing.JButton();
        logo_usu = new javax.swing.JLabel();
        inventario = new javax.swing.JPanel();
        ver_inven = new javax.swing.JButton();
        logo_inv = new javax.swing.JLabel();
        reportes = new javax.swing.JPanel();
        ver_report = new javax.swing.JButton();
        logo_repor = new javax.swing.JLabel();
        proved = new javax.swing.JPanel();
        ver_prov = new javax.swing.JButton();
        logo_prov = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        ver_clien = new javax.swing.JButton();
        logo_clien = new javax.swing.JLabel();
        ajustes = new javax.swing.JPanel();
        setting = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuario_vista.setBackground(new java.awt.Color(204, 204, 255));

        icono_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/admin.png"))); // NOI18N

        user_nombre.setText("Hola, [usuario]");

        cambia_user.setText("Cerrar sesión");
        cambia_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambia_userActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout usuario_vistaLayout = new javax.swing.GroupLayout(usuario_vista);
        usuario_vista.setLayout(usuario_vistaLayout);
        usuario_vistaLayout.setHorizontalGroup(
            usuario_vistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuario_vistaLayout.createSequentialGroup()
                .addGroup(usuario_vistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cambia_user)
                    .addGroup(usuario_vistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(usuario_vistaLayout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addComponent(icono_user))
                        .addGroup(usuario_vistaLayout.createSequentialGroup()
                            .addGap(55, 55, 55)
                            .addComponent(user_nombre))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        usuario_vistaLayout.setVerticalGroup(
            usuario_vistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuario_vistaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(icono_user, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(user_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cambia_user)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        panel.add(usuario_vista, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 370));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(2, 3));

        usuarios.setBackground(new java.awt.Color(255, 255, 255));
        usuarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        ver_usu.setText("Ver Usuarios");
        ver_usu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_usuActionPerformed(evt);
            }
        });

        logo_usu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/grupo.png"))); // NOI18N

        javax.swing.GroupLayout usuariosLayout = new javax.swing.GroupLayout(usuarios);
        usuarios.setLayout(usuariosLayout);
        usuariosLayout.setHorizontalGroup(
            usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuariosLayout.createSequentialGroup()
                .addGroup(usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usuariosLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(ver_usu))
                    .addGroup(usuariosLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(logo_usu)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        usuariosLayout.setVerticalGroup(
            usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usuariosLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(logo_usu, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ver_usu)
                .addGap(17, 17, 17))
        );

        jPanel1.add(usuarios);

        inventario.setBackground(new java.awt.Color(255, 255, 255));
        inventario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        ver_inven.setText("Ver Inventario");
        ver_inven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_invenActionPerformed(evt);
            }
        });

        logo_inv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inventario.png"))); // NOI18N

        javax.swing.GroupLayout inventarioLayout = new javax.swing.GroupLayout(inventario);
        inventario.setLayout(inventarioLayout);
        inventarioLayout.setHorizontalGroup(
            inventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventarioLayout.createSequentialGroup()
                .addGroup(inventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inventarioLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(ver_inven))
                    .addGroup(inventarioLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(logo_inv)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        inventarioLayout.setVerticalGroup(
            inventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inventarioLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(logo_inv)
                .addGap(18, 18, 18)
                .addComponent(ver_inven)
                .addGap(17, 17, 17))
        );

        jPanel1.add(inventario);

        reportes.setBackground(new java.awt.Color(255, 255, 255));
        reportes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        ver_report.setText("Ver Reportes");

        logo_repor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte.png"))); // NOI18N

        javax.swing.GroupLayout reportesLayout = new javax.swing.GroupLayout(reportes);
        reportes.setLayout(reportesLayout);
        reportesLayout.setHorizontalGroup(
            reportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportesLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(ver_report)
                .addGap(24, 24, 24))
            .addGroup(reportesLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(logo_repor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        reportesLayout.setVerticalGroup(
            reportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportesLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(logo_repor)
                .addGap(18, 18, 18)
                .addComponent(ver_report)
                .addGap(17, 17, 17))
        );

        jPanel1.add(reportes);

        proved.setBackground(new java.awt.Color(255, 255, 255));
        proved.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        ver_prov.setText("Ver Proveedores");
        ver_prov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_provActionPerformed(evt);
            }
        });

        logo_prov.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/proveedor.png"))); // NOI18N

        javax.swing.GroupLayout provedLayout = new javax.swing.GroupLayout(proved);
        proved.setLayout(provedLayout);
        provedLayout.setHorizontalGroup(
            provedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(provedLayout.createSequentialGroup()
                .addGroup(provedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(provedLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(ver_prov))
                    .addGroup(provedLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(logo_prov)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        provedLayout.setVerticalGroup(
            provedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, provedLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(logo_prov)
                .addGap(26, 26, 26)
                .addComponent(ver_prov)
                .addGap(16, 16, 16))
        );

        jPanel1.add(proved);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        ver_clien.setText("Ver Clientes");
        ver_clien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_clienActionPerformed(evt);
            }
        });

        logo_clien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/compras.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(ver_clien)
                .addGap(24, 24, 24))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(logo_clien)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(logo_clien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(ver_clien)
                .addGap(16, 16, 16))
        );

        jPanel1.add(jPanel3);

        ajustes.setBackground(new java.awt.Color(255, 255, 255));
        ajustes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        setting.setText("Ajustes");
        setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/preparar.png"))); // NOI18N

        javax.swing.GroupLayout ajustesLayout = new javax.swing.GroupLayout(ajustes);
        ajustes.setLayout(ajustesLayout);
        ajustesLayout.setHorizontalGroup(
            ajustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajustesLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(55, 55, 55))
            .addGroup(ajustesLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(setting)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ajustesLayout.setVerticalGroup(
            ajustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ajustesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(setting)
                .addGap(16, 16, 16))
        );

        jPanel1.add(ajustes);

        panel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 530, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cambia_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambia_userActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_cambia_userActionPerformed

    private void settingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_settingActionPerformed

    private void ver_usuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_usuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Admin_Clientes().setVisible(true);
    }//GEN-LAST:event_ver_usuActionPerformed

    private void ver_invenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_invenActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Admin_Inventario().setVisible(true);
    }//GEN-LAST:event_ver_invenActionPerformed

    private void ver_provActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_provActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Admin_Proveedores().setVisible(true);
    }//GEN-LAST:event_ver_provActionPerformed

    private void ver_clienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_clienActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Admin_Usuarios().setVisible(true);
    }//GEN-LAST:event_ver_clienActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Login_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Login_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Login_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Login_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Login_Admin().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ajustes;
    private javax.swing.JButton cambia_user;
    private javax.swing.JLabel icono_user;
    private javax.swing.JPanel inventario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel logo_clien;
    private javax.swing.JLabel logo_inv;
    private javax.swing.JLabel logo_prov;
    private javax.swing.JLabel logo_repor;
    private javax.swing.JLabel logo_usu;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel proved;
    private javax.swing.JPanel reportes;
    private javax.swing.JButton setting;
    private javax.swing.JLabel user_nombre;
    private javax.swing.JPanel usuario_vista;
    private javax.swing.JPanel usuarios;
    private javax.swing.JButton ver_clien;
    private javax.swing.JButton ver_inven;
    private javax.swing.JButton ver_prov;
    private javax.swing.JButton ver_report;
    private javax.swing.JButton ver_usu;
    // End of variables declaration//GEN-END:variables
}
